import enum
from dataclasses import dataclass

class TokenType(enum.Enum):
    

    KEYWORD_BEGIN_TRANSACTION = "BEGIN TRANSACTION"
    KEYWORD_ORDER_BY = "ORDER BY"
    KEYWORD_SELECT = "SELECT"
    KEYWORD_FROM = "FROM"
    KEYWORD_WHERE = "WHERE"
    KEYWORD_EXIST = "EXIST"
    KEYWORD_JOIN = "JOIN"
    KEYWORD_ON = "ON"
    KEYWORD_IN = "IN"
    KEYWORD_NATURAL = "NATURAL"
    KEYWORD_UPDATE = "UPDATE"
    KEYWORD_SET = "SET"
    KEYWORD_INSERT = "INSERT"
    KEYWORD_INTO = "INTO"
    KEYWORD_DELETE = "DELETE"
    KEYWORD_CREATE = "CREATE"
    KEYWORD_TABLE = "TABLE"
    KEYWORD_DROP = "DROP"
    KEYWORD_CASCADE = "CASCADE"
    KEYWORD_RESTRICT = "RESTRICT"
    KEYWORD_AS = "AS"
    KEYWORD_INNER = "INNER"
    KEYWORD_EXISTS = "EXISTS"
    KEYWORD_BETWEEN = "BETWEEN"
    KEYWORD_IS = "IS"
    KEYWORD_LIKE = "LIKE"
    KEYWORD_FOREIGN = "FOREIGN"
    KEYWORD_PRIMARY = "PRIMARY"
    KEYWORD_KEY = "KEY"
    KEYWORD_REFERENCES = "REFERENCES"
    KEYWORD_LIMIT = "LIMIT"
    KEYWORD_COMMIT = "COMMIT"
    KEYWORD_AND = "AND"
    KEYWORD_OR = "OR"
    KEYWORD_NOT = "NOT"

    OPERATOR_NOT_EQUAL = "<>"
    OPERATOR_GREATER_EQUAL = ">="
    OPERATOR_LESS_EQUAL = "<="
    OPERATOR_EQUAL = "="
    OPERATOR_GREATER_THAN = ">"
    OPERATOR_LESS_THAN = "<"
    OPERATOR_PLUS = "+"
    OPERATOR_MINUS = "-"
    OPERATOR_MULTIPLY = "*"
    OPERATOR_DIVIDE = "/"
    
    IDENTIFIER = "IDENTIFIER"
    
    LITERAL_STRING = "LITERAL_STRING"
    LITERAL_NUMBER = "LITERAL_NUMBER"
    LITERAL_BOOLEAN = "LITERAL_BOOLEAN"
    LITERAL_NULL = "LITERAL_NULL"
    
    DELIMITER_COMMA = ","
    DELIMITER_SEMICOLON = ";"
    DELIMITER_LPAREN = "("
    DELIMITER_RPAREN = ")"
    
    UNKNOWN = "UNKNOWN"
    EOF = "EOF"

@dataclass
class Token:

    type: TokenType
    value: str
    line: int
    column: int 
